### PR TITLE
formula: :tada: update envd to 0.2.0-alpha.14

### PR DESCRIPTION
**Pull request by zwpaper**
drop the version one, we do not have to keep historical version currently

Signed-off-by: Wei Zhang <kweizh@gmail.com>

### CODE REVIEW

**Comment by gaocegege** [comment]
Thanks! Maybe we should have a CICD process to automate this.

**Comment by rudeigerc** [comment]
As mentioned in tensorchord/envd#455, `goreleaser` would handle the release when the stable version is released. 

BTW, we could update `skip_upload` parameter to support syncing pre-released versions with `goreleaser`, but I think we should not let alpha/beta versions be synced with Homebrew Tap.

**Comment by rudeigerc** [comment]
Homebrew provides the `--head` flag to let users build the project from the source, which is not capable with `goreleaser`. If we would like to let users install pre-released versions we have to use an alternative way instead of the build-in `goreleaser` integration of Homebrew Tap.

**Comment by zwpaper** [comment]
oops, I was still confused why the CI was not working.

It is the auto skip_upload option preventing the update.

But we only have the alpha version available, maybe we should release the alpha to tap and let users access to the only releases

**Comment by rudeigerc** [comment]
> But we only have the alpha version available, maybe we should release the alpha to tap and let users access to the only releases

It's a probable solution but separating `envd` as two formulas still sounds a little bit weird. 😂 It would also introduce the cost of the installation due to the confliction between stable and alpha versions.

Since `envd` is under heavy development currently and the alpha releases account for the majority of releases, maybe we should enable syncing with alpha releases again? WDYT @gaocegege

**Comment by zwpaper** [comment]
as alpha is tagged as the released version, IMHO, we should publish it as brew releases.

according to the [goreleaser doc](https://goreleaser.com/customization/homebrew/#head-formulas), we may create a standalone head formula, let me try this later.

maybe we have some misunderstanding 🤣, I don't mean to split `envd` into 2 formulas, we should only keep the stable version once we have it.

as the alpha version is the only version we have, so that we should publish it into tap as the only release.

oh, after writing the content above, I found out that we have 2 formulas if we use a goreleaser one, and `head` one. but this is recommended as the goreleaser doc, it should be ok? @gaocegege

**Comment by zwpaper** [comment]
BTW, the reason I manually update the tap is that I can not wait to drop the golang dependency, it keeps failing me from installing `envd` by homebrew because I installed go manually 🤣

**Comment by rudeigerc** [comment]
Actually, the "formula" I have mentioned previously refers to the Homebrew Formula. I tried this way when we initialized this repository. This way would introduce two formulas `envd` and `envd-head`, and they have to be set conflicted by each other, otherwise, the linking of Homebrew may fail. Users have to uninstall the other version when they want to switch between stable and unstable versions. I do not recommend it. Currently, If we want to include alpha versions, my suggestion is to modify `skip_upload` parameter directly to trigger releases.

> BTW, the reason I manually update the tap is that I can not wait to drop the golang dependency, it keeps failing me from installing envd by homebrew because I installed go manually 🤣

That was my fault. 😂 `envd` does not need `go` when installing since it pulls the binary directly. I was trying to support building from source when installing at that time, so I added `go` to dependencies. We could remove the related code in `.goreleaser.yaml`. 

I still consider the most proper way is to use `--head` flag of Homebrew, but the Formula definition generated by goreleaser does not fit it.

**Comment by zwpaper** [comment]
got your point @rudeigerc, also, it's ok about the go dependency, it has been removed in the previous release.

how about setting `skip_upload` to `true`, and then modifying the generated formula, adding the `head` part in CI, and uploading to the git repo manually at last?

**Comment by rudeigerc** [comment]
> how about setting skip_upload to true, and then modifying the generated formula, adding the head part in CI, and uploading to the git repo manually at last?

That's the point. If we introduce `--head` flag, the formula has to be able to be built from the source. Homebrew uses bottles to refer to the binary in the mainstream repo, so it would not come up with this problem. However, the generation of Homebrew bottles is not supported by `goreleaser` currently.

But if we choose to modify `skip_upload` to release both alpha and stable versions I think we could ignore this temporarily.

**Comment by zwpaper** [comment]
one more option came up suddenly, we can fork goreleaser and optimize the brew ourselves😁, let me have a look at it in days.

**Comment by zwpaper** [comment]
after doing some research, maybe the current goreleaser way is the right way to go...

bottles is design as pre-built binary ON EACH platform BY homebrew, it contains a meta data file generated by homebrew, so that if we want to provide bottles, we have to set up an CI with each macOS, catalina, big sur, Monterey, etc., and Linux to built each bottles.

the current goreleaser can provider a binary installation on each platforms easily, seems to be a much solid way.

regarding to the building from source, a standalone tap like `envd-head` or `envd-dev` seems ok in a second thought,
we can setup a different binary name like the tap name, `envdhead` or `envdev`, so that users can install both envd and envd-head/envd-dev in the same time.

WDYT @gaocegege @rudeigerc

**Comment by gaocegege** [comment]
LGTM, as for the name, is there any naming convention in homebrew world? envd-head is confusing to me. Maybe envd-prerelease or envd-dev is better.

**Comment by zwpaper** [comment]
`head` suffix may come from the `git` `head` as we were building software from the `git head` code.

but it should be ok to name it anything only if it is more clear to users. users' understanding is much more important than the naming conventions.

**Pull request merged**
